### PR TITLE
add dog details

### PR DESCRIPTION
**Pull request by SereneSound**
I added the dog details needed for the report form. 

I wasn't able to test this locally because the container kept dying with this error message
(might be related to the build or might be happening in general - in `main` branch)
```
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/main.py", line 6, in <module>
    from app.routers.dogfinder import router as dogfinder_router
  File "/app/app/routers/dogfinder.py", line 144, in <module>
    auth = VerifyToken()
           ^^^^^^^^^^^^^
  File "/app/app/services/auth.py", line 48, in __init__
    self.config = get_auth0_config()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/services/auth.py", line 18, in get_auth0_config
    config = config["AUTH0"]
             ~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'AUTH0'
[18/10/2023 06:55:32.309] [INFO] [dogfinder]: Starting up the dogfinder router
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/main.py", line 6, in <module>
    from app.routers.dogfinder import router as dogfinder_router
  File "/app/app/routers/dogfinder.py", line 144, in <module>
    auth = VerifyToken()
           ^^^^^^^^^^^^^
  File "/app/app/services/auth.py", line 48, in __init__
    self.config = get_auth0_config()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/services/auth.py", line 18, in get_auth0_config
    config = config["AUTH0"]
             ~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'AUTH0'
[18/10/2023 06:56:34.504] [INFO] [dogfinder]: Starting up the dogfinder router
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 467, in load
    self.loaded_app = import_from_string(self.app)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app/main.py", line 6, in <module>
    from app.routers.dogfinder import router as dogfinder_router
  File "/app/app/routers/dogfinder.py", line 144, in <module>
    auth = VerifyToken()
           ^^^^^^^^^^^^^
  File "/app/app/services/auth.py", line 48, in __init__
    self.config = get_auth0_config()
                  ^^^^^^^^^^^^^^^^^^
  File "/app/app/services/auth.py", line 18, in get_auth0_config
    config = config["AUTH0"]
             ~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.11/configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'AUTH0'
```

### CODE REVIEW

**Review by itamar-cord — APPROVED** [review]

**Review by YanDav78 — CHANGES_REQUESTED** [review]
We can't merge this yet, we need to change the vectordb part, and we can't save it as one object of dog details, we need to have it in separate fields in order to filter by it.

**Comment by SereneSound** [comment]
@YanDav78 If we can't save this object to the VDB (btw I'd really like to understand why when you have the chance to explain), can you please remove the DogDetails object and pass these params flat to the VDB? just use this branch, I don't mind

**Comment by SereneSound** [comment]
@YanDav78 Oh, I see, now I see that weaviate works with schemas. Sorry I didn't spend too much time on this this morning when I worked on that, and I'm not able to test locally. 
Since we're at the beginning and there's no critical data in production, can I make the changes directly on the schema or should I use a [migrtaion](https://weaviate.io/developers/weaviate/configuration/schema-configuration) using `property.create`?

**Comment by SereneSound** [comment]
@YanDav78  I made the changes to the schema (assuming we can just reset the VDB without a migration. If this is not possible at this stage, I guess we need to make a migration like [this](https://weaviate.io/developers/weaviate/configuration/schema-configuration). correct?)

**Pull request merged**
