### PR TITLE
add reporter id & some reafctoring

### PR DESCRIPTION
**Pull request by SereneSound**
* Added reporter_id - this is coming from the "sub" property in `auth_result` This corresponds to the complete id in auth 0, which includes the connection type, as seen here:
Screenshot 2023-10-31 at 22 41 21

@YanDav78 I'm wondering if we should clean the `google-oauth2|` from the string or that it doesn't really matter. As you can see the `user_id` for them is the `user_id` and the connection type. A recursive definition. 

*Added exception_handler to main. This intercepts all uncaught exceptions from the application and wraps them. We could also clean the endpoints like this, but I didn't touch them for now.

### CODE REVIEW

**Comment by YanDav78** [comment]
@SereneSound I'm not an expert on this, but I have a question.
I assume that it would be possible to register/login with other identity providers.
If I will choose now to login with Facebook, will I have the same user id?
If so, we should save just the user id without the provider. 
If Not so I guess it does not matter much.

**Comment by SereneSound** [comment]
@YanDav78 I'm not sure actually. We need to check that. I think that the safest bet would be just to remove it. I'll clean it tomorrow morning. Is there anything else you saw in the PR?

**Comment by YanDav78** [comment]
Everything else looks good to me

**Comment by SereneSound** [comment]
@YanDav78 So I looked a bit into it and found [this](https://community.auth0.com/t/how-exactly-does-user-id-work-and-what-is-the-difference-between-the-top-level-user-id-and-the-ones-in-identities/38222/5). 

Basically what they're saying is that the user_id constructed as `provider|id` is configured such that the `id` part is unique **with respects** to the `provider` section. They say there's close to zero chance of collision even if you remove the prefix, but that it's safest to leave it with the prefix, unless we choose to make a custom `uuid` for the user. 
Thing is, from what they confirmed in this thread, this`user_id=provider|id` is determined on the first login - so even if the user adds more providers, the user_id stays the same. So it sounds safe to use it with the prefix

About creating custom uuid: it the link I sent here they refer to something called _rules_ in auth0, but this is **deprecated** and does not exist anymore in newer tenants (like us). So creating this is not as easy as copy-pasting the code and putting it there. 
There is a possibility of adding a custom claim to the JWT using a custom "Action", which is the successor of the "Rules". But they have a different syntax, and it would take a bit of digging around in their documentation. I'm just not sure it's worth the hussle if the `provider|id` pattern is safe enough. WDYT?

**Comment by YanDav78** [comment]
@SereneSound Yes I think it is better to keep the provider id. I'm not sure exactly how this works when a user is logging in with another provider but either way it will help us to attach it to the same user. so yes lets keep it as is.

**Review by YanDav78 — APPROVED** [review]

**Pull request merged**
